version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: project-pg
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
    network_mode: bridge
    ports:
      - 9000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
    driver: local
  pgadmin_data:
    driver: local
